version: 0.2

# buildspec for downloading required source code to S3 - as part of codepipeline build

phases:
  install:
    runtime-versions:
      # https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
      nodejs: 18
    commands:
      - echo install

      - echo "install terraform"
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
#     we only work within code
      - cd code

  post_build:
    commands:
      - echo post_build

      - echo "initialize terraform"
      - cd terraform

      - echo $PROJECT_NAME
      - echo $GITHUB_REPO
      - echo $BRANCH
      - echo $ARTIFACTS
      - terraform init -backend-config="bucket=$ARTIFACTS" -backend-config="key=$BRANCH/terraform/lambda.tfstate"

      - echo "apply terraform"
      #      - terraform plan -var "project_name=$PROJECT_NAME" -var "github_repo=$GITHUB_REPO"  -var "branch=$BRANCH"  -var "artifacts=$ARTIFACTS"
      - terraform apply -auto-approve -var "project_name=$PROJECT_NAME" -var "github_repo=$GITHUB_REPO" -var "branch=$BRANCH"  -var "artifacts=$ARTIFACTS"
